require('dotenv').config();
const WebSocketClient = require('./WSClient');
const { wsPrivStagURL } = require('../constants');
const secretKey = process.env.API_SECRET;
const apiKey = process.env.API_KEY;

// Configurable Parameters
const topic = 'balance' // Subscription Topics (https://docs.woo.org/#websocket-api-v2): balance / executionreport / algoexecutionreportv2 / position / marginassignment
const clientId = 'clientID123'; // ClientID generated by client: eg. clientID123
const client = new WebSocketClient(wsPrivStagURL); // Private Websocket URL for Production or Staging: wsPrivProdURL / wsPrivStagURL

client.authenticate(clientId, apiKey, secretKey)
    .then(() => {
        client.subscribe(clientId, topic);
    })
    .catch(error => {
        console.error('Authentication failed:', error);
    });