const WebSocketClient = require('./WSClient');
const { wsPubStagURL } = require('../constants');


// Configurable Parameters
const topic = 'SPOT_BTC_USDT@trade'; // Subscription Topics (https://docs.woo.org/#websocket-api-v2): orderbook / orderbook100 / aggbook10 / aggbook100 / aggbook1000 / ticker / tickers / bbo / trade / kline_1m / kline_5m / kline_15m / kline_30m / kline_1h / kline_1d / kline_1w / kline_1M / indexprice / markprice / estfundingrate / openinterests / markprices
const clientId = 'clientID123'; // ClientID generated by client: eg. clientID123
const client = new WebSocketClient(wsPubStagURL); // Public Websocket URL for Production or Staging: wsPubProdURL / wsPubStagURL

client.subscribe(clientId, topic);